export const MECH_ID = {
  mc01Lever: "mc01_lever",
  mc01Ballast: "mc01_ballast",
  mc01Lift: "mc01_lift",
  mc01Rope: "mc01_rope",
  entryRocker: "entry_rocker",
  entryPawl: "entry_pawl",
  entryPawlCable: "entry_pawl_cable",
  transferCarriage: "transfer_carriage",
  transferCounterweight: "transfer_counterweight",
  transferRope: "transfer_rope",
  bridgeRelease: "bridge_release",
  bridgePawl: "bridge_pawl",
  bridgePawlCable: "bridge_pawl_cable",
  bridge: "bridge",
  springShuttleLatch: "spring_shuttle_latch",
  springShuttle: "spring_shuttle",
  mc05EntryRocker: "mc05_entry_rocker",
  mc05Pawl: "mc05_pawl",
  mc05PawlCable: "mc05_pawl_cable",
  mc05Bascule: "mc05_bascule",
  mc05Ballast: "mc05_ballast",
  mc05Table: "mc05_table",
  mc05TransferCable: "mc05_transfer_cable",
  mc05BrakeHandle: "mc05_brake_handle",
  mc06Rotor: "mc06_rotor",
  mc06Bridge: "mc06_bridge",
  mc06Dropweight: "mc06_dropweight",
  mc06DriveCable: "mc06_drive_cable",
  mc06BrakeHandle: "mc06_brake_handle",
  mc07BrakeHandle: "mc07_brake_handle",
  mc07Ascender: "mc07_ascender",
  mc07Countercar: "mc07_countercar",
  mc07BalanceCable: "mc07_balance_cable",
  mc07Cradle: "mc07_cradle",
  mc08Latch: "mc08_latch",
  mc08Ring: "mc08_ring",
  mc08Ballast: "mc08_ballast",
  mc08Helix: "mc08_helix",
  mc09Valve: "mc09_valve",
  mc09Ram: "mc09_ram",
  mc10Flywheel: "mc10_flywheel",
  mc10Governor: "mc10_governor",
  mc10Bridge: "mc10_bridge",
} as const;

export type MechanicalId = (typeof MECH_ID)[keyof typeof MECH_ID];